spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:arenacup}?currentSchema=auth_service
    username: ${POSTGRES_USER:arenacup}
    password: ${POSTGRES_PASSWORD:arenacup}
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
    properties:
      hibernate:
        default_schema: auth_service
        globally_quoted_identifiers: true
        hbm2ddl.create_namespaces: true

server:
  port: ${SERVER_PORT:9998}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    register-with-eureka: ${EUREKA_CLIENT_ENABLED:true}
    fetch-registry: ${EUREKA_CLIENT_ENABLED:true}

management:
  endpoints:
    web:
      exposure:
        include: health,info
